apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
      app: nginx-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nging
   template:
      metadata:
         labels:
            app: ngingx
      spec:
         containers:
         - image: nginx
           name: nginx
